apiVersion: v1
kind: Pod
metadata:
  name: telnet
spec:
  containers:
  - name: telnet
    image: realworld/telnet
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
